from __future__ import annotations

import json
import shutil
from datetime import datetime
from pathlib import Path
from urllib.parse import quote

import openpyxl


ROOT = Path(__file__).resolve().parents[1]
WORKBOOK_PATH = ROOT / "cz_rostliny_rozsireny_dataset_v6_jadro_bezne_trvanlive.xlsx"
MEDIA_MANIFEST_PATH = ROOT / "app" / "media" / "plant_media.json"


SOURCE_ROWS = [
    {
        "zdroj_id": "S79",
        "nazev": "PFAF: Fagus sylvatica",
        "url": "https://pfaf.org/User/plant.aspx?LatinName=Fagus+sylvatica",
        "poznamka": "Kurátorovaný zdroj pro mladé bukové listy jako jarní potravní použití a další jedlé části buku.",
    },
    {
        "zdroj_id": "S80",
        "nazev": "PFAF: Crataegus monogyna",
        "url": "https://pfaf.org/user/plant.aspx?latinname=Crataegus+monogyna",
        "poznamka": "Kurátorovaný zdroj pro jedlé mladé výhonky hlohu a nálev ze sušených listů.",
    },
    {
        "zdroj_id": "S81",
        "nazev": "PFAF: Cardamine pratensis",
        "url": "https://pfaf.org/User/Plant.aspx?LatinName=Cardamine+pratensis",
        "poznamka": "Kurátorovaný zdroj pro jarní potravní využití řeřišnice luční.",
    },
    {
        "zdroj_id": "S82",
        "nazev": "PFAF: Allium schoenoprasum",
        "url": "https://pfaf.org/User/plant.aspx?latinname=Allium+schoenoprasum",
        "poznamka": "Kurátorovaný zdroj pro pažitku včetně čerstvého i sušeného kulinárního použití.",
    },
    {
        "zdroj_id": "S83",
        "nazev": "PFAF: Tilia cordata",
        "url": "https://pfaf.org/user/plant.aspx?latinname=tilia+cordata",
        "poznamka": "Kurátorovaný zdroj pro mladé lipové listy a jarní mízu s možností odpaření na sirup.",
    },
    {
        "zdroj_id": "S84",
        "nazev": "PFAF: Pulmonaria officinalis",
        "url": "https://pfaf.org/user/plant.aspx?latinname=Pulmonaria+officinalis",
        "poznamka": "Kurátorovaný zdroj pro plicník lékařský jako méně známou jarní listovou zeleninu.",
    },
    {
        "zdroj_id": "S85",
        "nazev": "PFAF: Cardamine hirsuta",
        "url": "https://pfaf.org/user/Plant.aspx?LatinName=Cardamine+hirsuta",
        "poznamka": "Kurátorovaný zdroj pro řeřišničník chlupatý, včetně listů a květů syrových i vařených.",
    },
    {
        "zdroj_id": "S86",
        "nazev": "PFAF: Veronica beccabunga",
        "url": "https://pfaf.org/USER/Plant.aspx?LatinName=Veronica+beccabunga",
        "poznamka": "Kurátorovaný zdroj pro rozrazil potoční jako velmi málo známou mokřadní jedlou zeleň.",
    },
    {
        "zdroj_id": "S87",
        "nazev": "PFAF: Anthriscus sylvestris",
        "url": "https://pfaf.org/user/Plant.aspx?LatinName=Anthriscus+sylvestris",
        "poznamka": "Kurátorovaný zdroj pro kerblík lesní, ale i pro důrazné upozornění na záměnu s jedovatými miříkovitými.",
    },
    {
        "zdroj_id": "S88",
        "nazev": "PFAF: Ulmus",
        "url": "https://pfaf.org/user/Plant.aspx?LatinName=Ulmus",
        "poznamka": "Kurátorovaný zdroj pro jarní jedlé listy jilmu; v datasetu aplikováno na jilm horský jako český zástupce.",
    },
    {
        "zdroj_id": "S89",
        "nazev": "PFAF: Bunias orientalis",
        "url": "https://pfaf.org/user/Plant.aspx?LatinName=Bunias+orientalis",
        "poznamka": "Kurátorovaný zdroj pro rukevník východní jako neobvyklou jarní brukvovitou zeleninu.",
    },
    {
        "zdroj_id": "S90",
        "nazev": "PFAF: Lapsana communis",
        "url": "https://pfaf.org/User/Plant.aspx?LatinName=Lapsana+communis",
        "poznamka": "Kurátorovaný zdroj pro kapustku obecnou jako velmi nenápadnou jarní listovou zeleninu z ruderálních a městských míst.",
    },
    {
        "zdroj_id": "S91",
        "nazev": "PFAF: Barbarea vulgaris",
        "url": "https://pfaf.org/user/Plant.aspx?LatinName=Barbarea+vulgaris",
        "poznamka": "Kurátorovaný zdroj pro barborku obecnou včetně jarních listů a květních výhonů.",
    },
    {
        "zdroj_id": "S92",
        "nazev": "PFAF: Hesperis matronalis",
        "url": "https://pfaf.org/user/Plant.aspx?LatinName=Hesperis+Matronalis",
        "poznamka": "Kurátorovaný zdroj pro večernici vonnou jako zahradně-zplaňující, ale jedlou jarní brukvovitou rostlinu.",
    },
    {
        "zdroj_id": "S93",
        "nazev": "PFAF: Campanula rapunculoides",
        "url": "https://pfaf.org/User/plant.aspx?latinname=Campanula+rapunculoides",
        "poznamka": "Kurátorovaný zdroj pro zvonek řepkovitý jako velmi málo známou listovou a výhonkovou jedlost.",
    },
    {
        "zdroj_id": "S94",
        "nazev": "PFAF: Lepidium campestre",
        "url": "https://pfaf.org/user/Plant.aspx?LatinName=Lepidium+campestre",
        "poznamka": "Kurátorovaný zdroj pro řeřichu rolničkovou jako časnou peprnou brukvovitou zeleninu.",
    },
    {
        "zdroj_id": "S95",
        "nazev": "PFAF: Campanula trachelium",
        "url": "https://pfaf.org/user/Plant.aspx?LatinName=Campanula+trachelium",
        "poznamka": "Kurátorovaný zdroj pro zvonek kopřivolistý jako regionálně doloženou, ale okrajovou listovou zeleninu.",
    },
]


STARTER_ROWS = [
    {
        "record_id": "R238",
        "vedecky_nazev": "Fagus sylvatica",
        "cesky_nazev": "buk lesní",
        "status_v_CR": "původní, běžný",
        "cast_rostliny": "mladé listy",
        "domena": "potrava",
        "poddomena": "mladé bukové listy do salátu",
        "status_znalosti": "méně známé",
        "aplikovatelnost_v_CR": "vysoká",
        "typicke_lokality_v_CR": "bučiny, lesní okraje, parky, aleje",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "zcela mladé světle zelené a ještě jemné listy",
        "zpusob_pripravy_nebo_vyuziti": "Sbírat jen nejmladší listy a používat je čerstvé po menším množství do míchaných salátů nebo na chléb.",
        "cilovy_efekt": "Jemná jarní salátová zeleň s mírně nakyslou chutí.",
        "chutovy_profil": "jemná, lehce nakyslá, zelená",
        "vonny_profil": "svěže listový",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sbírat jen opravdu mladé listy; starší rychle tuhnou a ztrácejí kulinární kvalitu.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Běžný nechráněný druh; netrhat ve velkém z mladých semenáčků a v chráněných územích respektovat místní režim.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S79",
        "zdroj_id_2": "",
        "poznamka": "Dubnové rozšíření repertoáru o jemnou lesní listovou zeleninu.",
    },
    {
        "record_id": "R239",
        "vedecky_nazev": "Crataegus monogyna Jacq. / C. laevigata (Poir.) DC.",
        "cesky_nazev": "hloh obecný / jednosemenný",
        "status_v_CR": "původní, běžný",
        "cast_rostliny": "mladé listy a výhonky",
        "domena": "potrava",
        "poddomena": "mladé listy a výhonky do salátu",
        "status_znalosti": "méně známé",
        "aplikovatelnost_v_CR": "vysoká",
        "typicke_lokality_v_CR": "meze, křoviny, remízky, lesní lemy",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "rašící špičky a mladé listy před ztuhnutím",
        "zpusob_pripravy_nebo_vyuziti": "Mladé špičky a listy jíst čerstvé po menším množství jako jemně oříškovou salátovou příměs.",
        "cilovy_efekt": "Jarní čerstvá zeleň s jemně oříškovým tónem.",
        "chutovy_profil": "jemná, lehce oříšková",
        "vonny_profil": "slabě zelený",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Netrhat nadměrně celé větve a sbírat jen bezpečně určený hloh.",
        "kontraindikace_interakce": "U skutečných kardiálních obtíží nejde o náhradu odborné péče.",
        "legalita_poznamka_CR": "Běžný nechráněný druh; sbírat střídmě a neničit keře.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S80",
        "zdroj_id_2": "",
        "poznamka": "Rozšíření dubna o jedlou jarní část hlohu, ne jen plody a EMA drogu.",
    },
    {
        "record_id": "R240",
        "vedecky_nazev": "Crataegus monogyna Jacq. / C. laevigata (Poir.) DC.",
        "cesky_nazev": "hloh obecný / jednosemenný",
        "status_v_CR": "původní, běžný",
        "cast_rostliny": "mladé listy",
        "domena": "pití",
        "poddomena": "sušené listy na nálev / čajovou náhražku",
        "status_znalosti": "méně známé",
        "aplikovatelnost_v_CR": "vysoká",
        "typicke_lokality_v_CR": "meze, křoviny, remízky, lesní lemy",
        "obdobi_ziskani": "IV–V + sušení",
        "fenologicka_faze": "mladé listy v době jarního růstu",
        "zpusob_pripravy_nebo_vyuziti": "Mladé listy natrhat na jaře, usušit v tenké vrstvě a později používat do jednoduchého nálevu nebo čajových směsí.",
        "cilovy_efekt": "Jemná bylinná čajová složka z jarních listů hlohu.",
        "chutovy_profil": "jemná, lehce svíravá",
        "vonny_profil": "slabě zelený",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Netrhat nadměrně celé větve; u skutečných srdečních obtíží nejde o samoléčbu.",
        "kontraindikace_interakce": "Při bolesti na hrudi, dušnosti nebo otocích vždy lékař.",
        "legalita_poznamka_CR": "Běžný nechráněný druh; sbírat jednotlivé listy a neničit keře.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S80",
        "zdroj_id_2": "",
        "poznamka": "Doplňuje dubnové použití hlohu i o trvanlivou formu.",
    },
    {
        "record_id": "R241",
        "vedecky_nazev": "Cardamine pratensis",
        "cesky_nazev": "řeřišnice luční",
        "status_v_CR": "původní, běžná",
        "cast_rostliny": "mladé listy, výhonky a květy",
        "domena": "potrava",
        "poddomena": "listy a květy do jarního salátu",
        "status_znalosti": "méně známé",
        "aplikovatelnost_v_CR": "vysoká",
        "typicke_lokality_v_CR": "vlhké louky, příkopy, nivy, podmáčené okraje cest",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "mladé listy a čerstvě rozvinuté květy",
        "zpusob_pripravy_nebo_vyuziti": "Listy, mladé výhonky a květy používat po menším množství do salátů, pomazánek nebo na chléb jako jemně řeřišnicovou složku.",
        "cilovy_efekt": "Pepřnatá jarní zeleň pro svěží saláty.",
        "chutovy_profil": "jemně peprná, řeřišnicová",
        "vonny_profil": "svěže brukvovitý",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sbírat jen bezpečně určený druh a mimo znečištěná vlhká stanoviště.",
        "kontraindikace_interakce": "U citlivých osob opatrnost při vyšším množství brukvovitých.",
        "legalita_poznamka_CR": "Běžný sběr v malém množství mimo chráněné lokality a bez poškozování celých trsů.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S81",
        "zdroj_id_2": "",
        "poznamka": "Nový dubnový druh se silnou sezónností vlhkých luk.",
    },
    {
        "record_id": "R242",
        "vedecky_nazev": "Allium schoenoprasum",
        "cesky_nazev": "pažitka pobřežní",
        "status_v_CR": "původní, lokálně vzácnější i pěstovaná",
        "cast_rostliny": "listy a květy",
        "domena": "potrava",
        "poddomena": "čerstvá nať / sušení / mražení",
        "status_znalosti": "mainstream",
        "aplikovatelnost_v_CR": "vysoká",
        "typicke_lokality_v_CR": "zahrady, záhony, bylinkové výsadby; ve volné přírodě jen lokálně",
        "obdobi_ziskani": "IV–VI",
        "fenologicka_faze": "čerstvá jemná nať a mladé květy",
        "zpusob_pripravy_nebo_vyuziti": "Část použít čerstvě jako jarní nať, část nasekat a zamrazit nebo usušit pro pozdější dochucování polévek, pomazánek a tvarohu.",
        "cilovy_efekt": "Spolehlivá cibulová nať pro jarní kuchyni i zásobu.",
        "chutovy_profil": "jemně cibulová, svěží",
        "vonny_profil": "čistě allium",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Ve volné přírodě nepřetěžovat drobné populace; sbírat jen bezpečně určenou pažitku.",
        "kontraindikace_interakce": "Opatrnost u citlivosti na česnekovité.",
        "legalita_poznamka_CR": "Pro praktické použití preferovat pěstovanou pažitku ze zahrady nebo trhu; ve volné přírodě sbírat jen tam, kde je druh běžný a sběr je legální.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S82",
        "zdroj_id_2": "",
        "poznamka": "Dubnové rozšíření se silným přesahem do dlouhodobého kuchyňského zpracování.",
    },
    {
        "record_id": "R243",
        "vedecky_nazev": "Tilia cordata / Tilia platyphyllos",
        "cesky_nazev": "lípa srdčitá / lípa velkolistá",
        "status_v_CR": "původní, běžný",
        "cast_rostliny": "mladé listy",
        "domena": "potrava",
        "poddomena": "mladé listy do salátu / na chléb",
        "status_znalosti": "méně známé",
        "aplikovatelnost_v_CR": "vysoká",
        "typicke_lokality_v_CR": "listnaté lesy, lesní lemy, parky, aleje, staré výsadby",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "právě rozvinuté měkké listy, ještě před zhrubnutím",
        "zpusob_pripravy_nebo_vyuziti": "Sbírat jen nejmladší měkké listy a používat je čerstvé do míchaných salátů nebo jako jemnou vrstvu do sendvičů a na chléb.",
        "cilovy_efekt": "Jemná stromová listová zelenina pro dubnovou kuchyni.",
        "chutovy_profil": "jemná, lehce nasládlá, mírně slizovitá",
        "vonny_profil": "slabě zelený",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Starší listy rychle tuhnou a ztrácejí kvalitu; nesbírat z prašných uličních stromů.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Běžný nechráněný druh; sbírat střídmě a nepoškozovat mladé výhony ani uliční stromořadí.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S83",
        "zdroj_id_2": "",
        "poznamka": "Rozšiřuje duben o velmi použitelnou, ale málo zmiňovanou stromovou zeleninu.",
    },
    {
        "record_id": "R244",
        "vedecky_nazev": "Tilia cordata / Tilia platyphyllos",
        "cesky_nazev": "lípa srdčitá / lípa velkolistá",
        "status_v_CR": "původní, běžný",
        "cast_rostliny": "míza",
        "domena": "pití",
        "poddomena": "jarní míza / odpaření na sirup",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "nízká až střední",
        "typicke_lokality_v_CR": "listnaté lesy, parky, aleje, staré výsadby",
        "obdobi_ziskani": "III–IV + odpaření",
        "fenologicka_faze": "krátké období jarního toku mízy před plným olistěním",
        "zpusob_pripravy_nebo_vyuziti": "Pouze velmi šetrně a jen tam, kde je odběr legální: malé množství mízy lze pít čerstvé nebo pomalu odpařit na sladší koncentrát či sirup.",
        "cilovy_efekt": "Experimentální jarní stromový nápoj a malá zásoba lipového sirupu.",
        "chutovy_profil": "jemně sladká, vodnatá",
        "vonny_profil": "slabě dřevitý",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Nenavrtávat veřejné ani cizí stromy; odběr může strom poškodit a výtěžnost bývá nízká.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Pouze na vlastních stromech nebo se souhlasem správce; v krajině nepoškozovat kmeny ani silnější větve.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S83",
        "zdroj_id_2": "",
        "poznamka": "Zařazeno jako dubnová niche znalost s explicitním důrazem na šetrnost odběru.",
    },
    {
        "record_id": "R245",
        "vedecky_nazev": "Pulmonaria officinalis",
        "cesky_nazev": "plicník lékařský",
        "status_v_CR": "původní, lokálně běžná",
        "cast_rostliny": "mladé listy",
        "domena": "potrava",
        "poddomena": "mladé listy syrové / krátce tepelně upravené",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "střední",
        "typicke_lokality_v_CR": "vlhčí listnaté lesy, křoviny, stinné lemy, místy i zahrady",
        "obdobi_ziskani": "III–IV",
        "fenologicka_faze": "nejmladší měkké listy před plným zhrubnutím",
        "zpusob_pripravy_nebo_vyuziti": "Listy po menším množství přidávat do míchaných salátů nebo krátce podusit a použít do polévek či zelených směsí.",
        "cilovy_efekt": "Jemná stinnolesní jarní zelenina pro rozšíření repertoáru.",
        "chutovy_profil": "spíše jemná, nevýrazná, lehce slizovitá",
        "vonny_profil": "slabě zelený",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Starší listy bývají chlupaté a méně příjemné; sbírat jen bezpečně určený plicník na čistém stanovišti.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Sbírat jen jednotlivé listy tam, kde je druh běžný, a ne z chemicky ošetřovaných okrasných výsadeb.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S84",
        "zdroj_id_2": "",
        "poznamka": "Vědomě přidaný tajnější dubnový druh mimo běžné foragerské seznamy.",
    },
    {
        "record_id": "R246",
        "vedecky_nazev": "Cardamine hirsuta",
        "cesky_nazev": "řeřišničník chlupatý",
        "status_v_CR": "původní, velmi běžná",
        "cast_rostliny": "mladé listy, lodyžky a květy",
        "domena": "potrava",
        "poddomena": "peprná příměs do salátu / na chléb",
        "status_znalosti": "méně známé",
        "aplikovatelnost_v_CR": "vysoká",
        "typicke_lokality_v_CR": "zahrady, záhony, spáry, květináče, zídky, narušená půda",
        "obdobi_ziskani": "III–V",
        "fenologicka_faze": "růžice a mladé kvetoucí lodyžky",
        "zpusob_pripravy_nebo_vyuziti": "Používat po menším množství jako ostrou řeřišnicovou složku do salátů, pomazánek, sendvičů a případně krátce povařit s jinou zelení.",
        "cilovy_efekt": "Snadno dostupná peprná jarní bylinka i z městských a zahradních mikrostanovišť.",
        "chutovy_profil": "peprná, řeřišnicová, lehce hořká",
        "vonny_profil": "svěže brukvovitý",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sbírat jen z čistých míst mimo psí zóny, výkaly a chemicky ošetřené záhony.",
        "kontraindikace_interakce": "U citlivých osob opatrnost při vyšším množství brukvovitých.",
        "legalita_poznamka_CR": "Velmi běžný nechráněný druh; pro praktické použití vhodný hlavně ze zahrad a čistých ruderálních míst.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S85",
        "zdroj_id_2": "",
        "poznamka": "Přidává velmi časnou a snadno dostupnou dubnovou řeřišnicovou chuť.",
    },
    {
        "record_id": "R247",
        "vedecky_nazev": "Veronica beccabunga",
        "cesky_nazev": "rozrazil potoční",
        "status_v_CR": "původní, lokálně běžná",
        "cast_rostliny": "mladé listy a vrcholky",
        "domena": "potrava",
        "poddomena": "listy syrové / krátce povařené ve směsi",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "nízká až střední",
        "typicke_lokality_v_CR": "čisté prameniště, mělčí potoky, mokré příkopy, vývěry, okraje tůní",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "čerstvé vrcholky na začátku jarního růstu",
        "zpusob_pripravy_nebo_vyuziti": "Používat jen z opravdu čisté tekoucí vody; po menším množství syrové do salátů spolu s výraznější zelení nebo krátce povařit s jinými jarními listy.",
        "cilovy_efekt": "Velmi neobvyklá mokřadní jarní zelenina pro specializovanější repertoár.",
        "chutovy_profil": "štiplavá, zelená, méně lahodná",
        "vonny_profil": "vlhce zelený",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Největší riziko je kontaminace vody; nesbírat z odvodňovacích struh, kanalizačních přítoků ani stojatých znečištěných vod.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Sbírat jen malé množství a jen z čistých lokalit bez poškozování mokřadního stanoviště.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S86",
        "zdroj_id_2": "",
        "poznamka": "Zařazeno schválně jako niche mokřadní jedlá rostlina s vysokým důrazem na hygienu stanoviště.",
    },
    {
        "record_id": "R248",
        "vedecky_nazev": "Anthriscus sylvestris",
        "cesky_nazev": "kerblík lesní",
        "status_v_CR": "původní, velmi běžný",
        "cast_rostliny": "mladé listy",
        "domena": "potrava",
        "poddomena": "listy syrové / vařené jako jarní bylina",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "střední",
        "typicke_lokality_v_CR": "okraje cest, příkopy, křoviny, lesní lemy, polostinná ruderální místa",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "mladé listy před plným vykvetením",
        "zpusob_pripravy_nebo_vyuziti": "Jen při naprosto jistém určení používat malé množství listů syrových jako příchuť nebo je krátce povařit s jinou jarní zelení.",
        "cilovy_efekt": "Kuriózní kerblíkově laděná jarní bylina pro pokročilejší sběrače.",
        "chutovy_profil": "zelená, lehce kerblíková, ne úplně vděčná",
        "vonny_profil": "jemně miříkovitý",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Vysoké riziko záměny s prudce jedovatými miříkovitými; bez odborné jistoty nesbírat vůbec.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Běžný nechráněný druh, ale prakticky jen pro sběrače s velmi dobrou znalostí čeledi Apiaceae.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S87",
        "zdroj_id_2": "",
        "poznamka": "Přidané záměrně jako pokročilejší a rizikovější dubnová položka se silným varováním.",
    },
    {
        "record_id": "R249",
        "vedecky_nazev": "Ulmus glabra",
        "cesky_nazev": "jilm horský",
        "status_v_CR": "původní, lokálně běžný",
        "cast_rostliny": "mladé listy",
        "domena": "potrava",
        "poddomena": "mladé listy syrové / krátce vařené",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "střední",
        "typicke_lokality_v_CR": "listnaté a suťové lesy, horské a podhorské lokality, parky, staré výsadby",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "rašící měkké listy krátce po otevření pupenů",
        "zpusob_pripravy_nebo_vyuziti": "Mladé listy používat v malém množství syrové do směsí nebo krátce tepelně upravit spolu s další jarní zeleninou.",
        "cilovy_efekt": "Velmi málo známé stromové rozšíření dubnové listové kuchyně.",
        "chutovy_profil": "jemná, lehce zelená",
        "vonny_profil": "slabě listový",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sběr má smysl jen v krátkém okně mladých listů a mimo silně znečištěná stanoviště.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Sbírat střídmě jednotlivé listy a nepoškozovat mladé stromky ani výsadby.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S88",
        "zdroj_id_2": "",
        "poznamka": "Rozšíření o další stromovou jedlost, tentokrát z výrazně okrajové znalostní vrstvy.",
    },
    {
        "record_id": "R250",
        "vedecky_nazev": "Bunias orientalis",
        "cesky_nazev": "rukevník východní",
        "status_v_CR": "zdomácnělý, lokálně běžný",
        "cast_rostliny": "mladé listy a lodyhy",
        "domena": "potrava",
        "poddomena": "mladé listy a lodyhy syrové / vařené",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "střední",
        "typicke_lokality_v_CR": "ruderální plochy, okraje cest, úhory, suché meze, náspy",
        "obdobi_ziskani": "III–V",
        "fenologicka_faze": "časné listy a měkké mladé lodyhy před kvetením",
        "zpusob_pripravy_nebo_vyuziti": "Mladé listy a lodyhy používat syrové do směsi nebo je krátce povařit jako brukvovitou zeleninu; syrové mohou některým lidem vadit.",
        "cilovy_efekt": "Neobvyklá jarní brukvovitá zelenina z nepůvodního, ale prakticky dostupného druhu.",
        "chutovy_profil": "mírně zelné, lehce pikantní",
        "vonny_profil": "brukvovitý",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sbírat před kvetením a vyhnout se prašným či chemicky zatíženým ruderálním lokalitám; syrové listy mohou být hůř stravitelné.",
        "kontraindikace_interakce": "Při citlivém trávení začínat malým množstvím.",
        "legalita_poznamka_CR": "Nepůvodní zdomácnělý druh; při sběru neroznášet semena ani části rostlin do nových míst.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S89",
        "zdroj_id_2": "",
        "poznamka": "Záměrně přidáno jako málo známá dubnová brukvovitá alternativa mimo mainstreamové seznamy.",
    },
    {
        "record_id": "R251",
        "vedecky_nazev": "Lapsana communis",
        "cesky_nazev": "kapustka obecná",
        "status_v_CR": "původní, velmi běžná",
        "cast_rostliny": "mladé listy a vrcholky",
        "domena": "potrava",
        "poddomena": "mladé listy syrové / vařené",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "vysoká",
        "typicke_lokality_v_CR": "zahrady, okraje cest, rumiště, zdi, křoviny, městské kouty",
        "obdobi_ziskani": "III–V",
        "fenologicka_faze": "nejmladší měkké listy a vrcholky před plným vytažením",
        "zpusob_pripravy_nebo_vyuziti": "Používat syrové po menším množství do směsí nebo krátce tepelně upravit jako jemnou zeleninu.",
        "cilovy_efekt": "Nenápadná jarní listová zelenina z běžných městských a ruderálních mikrostanovišť.",
        "chutovy_profil": "jemná, lehce nahořklá, salátová",
        "vonny_profil": "slabě zelený",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sbírat jen z čistých míst mimo psí zóny, okraje silnic a chemicky ošetřené plochy.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Velmi běžný nechráněný druh; vhodný hlavně ze zahradních a jinak čistých stanovišť.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S90",
        "zdroj_id_2": "",
        "poznamka": "Ultra-niche dubnová položka zaměřená na nenápadné městské a lemové jedlosti.",
    },
    {
        "record_id": "R252",
        "vedecky_nazev": "Barbarea vulgaris",
        "cesky_nazev": "barborka obecná",
        "status_v_CR": "původní, běžná",
        "cast_rostliny": "mladé listy a květní výhony",
        "domena": "potrava",
        "poddomena": "peprné listy a výhony syrové / vařené",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "střední",
        "typicke_lokality_v_CR": "vlhčí příkopy, okraje cest, louky, náspy, ruderální místa",
        "obdobi_ziskani": "III–V",
        "fenologicka_faze": "růžice a mladé výhony ještě před plným kvetením",
        "zpusob_pripravy_nebo_vyuziti": "Používat po menším množství syrové do směsí nebo krátce povařit; nejmladší části bývají chuťově nejlepší.",
        "cilovy_efekt": "Časná peprná brukvovitá složka do jarní kuchyně mimo mainstreamový repertoár.",
        "chutovy_profil": "peprná, řeřišnicová, lehce hořká",
        "vonny_profil": "brukvovitý",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Při větším množství může být chuť i stravitelnost problematičtější; sbírat jen z čistých lokalit.",
        "kontraindikace_interakce": "U citlivých osob opatrnost při vyšším množství brukvovitých.",
        "legalita_poznamka_CR": "Běžný nechráněný druh; sbírat střídmě a nevytrhávat celé růžice.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S91",
        "zdroj_id_2": "",
        "poznamka": "Ultra-niche dubnový brukvovitý list s ostřejší chutí než řeřišničník.",
    },
    {
        "record_id": "R253",
        "vedecky_nazev": "Hesperis matronalis",
        "cesky_nazev": "večernice vonná",
        "status_v_CR": "pěstovaná i zplaňující, lokálně běžná",
        "cast_rostliny": "mladé listy a květy",
        "domena": "potrava",
        "poddomena": "listy a květy do salátu / jako ozdoba",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "střední",
        "typicke_lokality_v_CR": "zahrady, staré výsadby, křoviny, zplaňující okraje cest a zdí",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "mladé listy a první rozvíjející se květy",
        "zpusob_pripravy_nebo_vyuziti": "Mladé listy po menším množství do směsí, květy jako jedlá ozdoba nebo jemná brukvovitá složka.",
        "cilovy_efekt": "Velmi okrajová jarní brukvovitá rostlina na pomezí zahrad a zplaňujících míst.",
        "chutovy_profil": "jemně peprná, lehce květinová",
        "vonny_profil": "slabě květinový",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Preferovat sběr z vlastních nebo známých neošetřených výsadeb; okrasné rostliny mohou být chemicky ošetřené.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Prakticky nejbezpečnější je sběr z vlastních výsadeb nebo legálně přístupných zplaňujících porostů.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S92",
        "zdroj_id_2": "",
        "poznamka": "Ultra-niche dubnová položka propojující jedlou zahradu a zplaňující flóru.",
    },
    {
        "record_id": "R254",
        "vedecky_nazev": "Campanula rapunculoides",
        "cesky_nazev": "zvonek řepkovitý",
        "status_v_CR": "původní, běžná lokálně",
        "cast_rostliny": "mladé listy a výhony",
        "domena": "potrava",
        "poddomena": "mladé listy a výhony syrové / vařené",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "střední",
        "typicke_lokality_v_CR": "světlé lesy, lemy, zahrady, zídky, starší kultivované plochy",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "časné přízemní listy a jemné výhony",
        "zpusob_pripravy_nebo_vyuziti": "Používat mladé listy a výhony syrové po menším množství nebo krátce povařit s jinou zeleninou.",
        "cilovy_efekt": "Velmi málo známá jarní listová jedlost z rodu, který se běžně s jídlem nespojuje.",
        "chutovy_profil": "jemná, lehce zelená",
        "vonny_profil": "slabý bylinný",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sbírat jen bezpečně určený zvonek a ne z okrasných výsadeb ošetřených postřiky.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Lokálně běžný nechráněný druh; sbírat střídmě a nevytrhávat celé rostliny.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S93",
        "zdroj_id_2": "",
        "poznamka": "Ultra-niche dubnová položka pro uživatele, kteří chtějí překročit běžný seznam jarních zelení.",
    },
    {
        "record_id": "R255",
        "vedecky_nazev": "Lepidium campestre",
        "cesky_nazev": "řeřicha rolničková",
        "status_v_CR": "původní, běžná lokálně",
        "cast_rostliny": "mladé listy, výhony a šešulky",
        "domena": "potrava",
        "poddomena": "časná peprná brukvovitá zeleň",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "střední",
        "typicke_lokality_v_CR": "suché meze, pole, ruderální a stepnější lokality, náspy",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "časné listy a mladé výhony; později i jemné šešulky",
        "zpusob_pripravy_nebo_vyuziti": "Mladé listy a výhony přidávat po menším množství do směsí nebo krátce povařit; chuť bývá výrazně řeřichová.",
        "cilovy_efekt": "Další velmi okrajová dubnová brukvovitá položka pro peprnější kuchyni.",
        "chutovy_profil": "výrazně peprná, řeřichová",
        "vonny_profil": "brukvovitý",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sbírat jen z čistých lokalit mimo intenzivně ošetřovaná pole a krajnice.",
        "kontraindikace_interakce": "U citlivých osob opatrnost při vyšším množství brukvovitých.",
        "legalita_poznamka_CR": "Lokálně běžný nechráněný druh; sbírat střídmě bez poškození celé populace.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S94",
        "zdroj_id_2": "",
        "poznamka": "Ultra-niche dubnová řeřichová alternativa mimo běžný domácí repertoár.",
    },
    {
        "record_id": "R256",
        "vedecky_nazev": "Campanula trachelium",
        "cesky_nazev": "zvonek kopřivolistý",
        "status_v_CR": "původní, běžná lokálně",
        "cast_rostliny": "mladé listy",
        "domena": "potrava",
        "poddomena": "jarní listy do směsí / krátce vařené",
        "status_znalosti": "téměř zapomenuté",
        "aplikovatelnost_v_CR": "nízká až střední",
        "typicke_lokality_v_CR": "světlé lesy, křoviny, stinnější lemy, staré zahrady",
        "obdobi_ziskani": "IV–V",
        "fenologicka_faze": "časné přízemní listy před zhrubnutím",
        "zpusob_pripravy_nebo_vyuziti": "Mladé listy přidávat po menším množství do směsí nebo krátce tepelně upravit s jinou zeleninou.",
        "cilovy_efekt": "Regionálně doložená, ale velmi okrajová jarní listová jedlost ze zvonků.",
        "chutovy_profil": "jemná, zelená",
        "vonny_profil": "slabý bylinný",
        "palivovy_potencial": "neaplikovatelné",
        "hlavni_rizika": "Sbírat jen mladé listy a jen při jistém určení; starší listy jsou tužší a méně vhodné.",
        "kontraindikace_interakce": "",
        "legalita_poznamka_CR": "Lokálně běžný nechráněný druh; sbírat po jednotlivých listech a nevytrhávat celé rostliny.",
        "dukaznost_typ": "kurátorovaný botanický zdroj",
        "dukaznost_skore": "D",
        "zdroj_id_1": "S95",
        "zdroj_id_2": "",
        "poznamka": "Ultra-niche dubnový doplněk pro hlubší, regionálněji znějící repertoár.",
    },
]


TRVANLIVE_ROWS = [
    {
        "record_id": "R240",
        "cesky_nazev": "hloh obecný / jednosemenný",
        "vedecky_nazev": "Crataegus monogyna Jacq. / C. laevigata (Poir.) DC.",
        "domena": "pití",
        "poddomena": "sušené listy na nálev / čajovou náhražku",
        "cast_rostliny": "mladé listy",
        "obdobi_ziskani": "IV–V + sušení",
        "typicke_lokality_v_CR": "meze, křoviny, remízky, lesní lemy",
        "forma_uchovani": "sušení listů na čajovou směs",
        "orientacni_trvanlivost": "6–12 měsíců",
        "poznamka_k_skladovani": "V suchu, temnu a dobře uzavřené nádobě.",
    },
    {
        "record_id": "R242",
        "cesky_nazev": "pažitka pobřežní",
        "vedecky_nazev": "Allium schoenoprasum",
        "domena": "potrava",
        "poddomena": "čerstvá nať / sušení / mražení",
        "cast_rostliny": "listy a květy",
        "obdobi_ziskani": "IV–VI",
        "typicke_lokality_v_CR": "zahrady, záhony, bylinkové výsadby; ve volné přírodě jen lokálně",
        "forma_uchovani": "sušení nebo mražení nasekaných listů",
        "orientacni_trvanlivost": "3–12 měsíců",
        "poznamka_k_skladovani": "Sušenou pažitku držet v suchu a temnu, mraženou v dobře uzavřeném obalu.",
    },
    {
        "record_id": "R244",
        "cesky_nazev": "lípa srdčitá / lípa velkolistá",
        "vedecky_nazev": "Tilia cordata / Tilia platyphyllos",
        "domena": "pití",
        "poddomena": "jarní míza / odpaření na sirup",
        "cast_rostliny": "míza",
        "obdobi_ziskani": "III–IV + odpaření",
        "typicke_lokality_v_CR": "listnaté lesy, parky, aleje, staré výsadby",
        "forma_uchovani": "odpaření mízy na koncentrát / sirup",
        "orientacni_trvanlivost": "6–12 měsíců",
        "poznamka_k_skladovani": "Po důkladném odpaření plnit horké do čistých lahví a skladovat v chladu a temnu.",
    },
]


PHOTO_UPDATES = {
    "plant_allium_ursinum": {
        "filename": "Allium ursinum.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Allium_ursinum.jpg",
        "alt": "Česnek medvědí v květu a listu",
        "caption": "Wikimedia Commons: Allium ursinum",
        "credit": "Meneerke bloem",
        "license": "CC BY-SA 4.0",
    },
    "plant_urtica_dioica": {
        "filename": "Urtica dioica Plant.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Urtica_dioica_Plant.jpg",
        "alt": "Kopřiva dvoudomá",
        "caption": "Wikimedia Commons: Urtica dioica",
        "credit": "Matildalove12",
        "license": "",
    },
    "plant_aegopodium_podagraria": {
        "filename": "Aegopodium podagraria.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Aegopodium_podagraria.jpg",
        "alt": "Bršlice kozí noha",
        "caption": "Wikimedia Commons: Aegopodium podagraria",
        "credit": "Kristian Peters -- Fabelfroh",
        "license": "GFDL",
    },
    "plant_taraxacum_officinale_agg": {
        "filename": "T. officinale.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:T._officinale.jpg",
        "alt": "Pampeliška lékařská",
        "caption": "Wikimedia Commons: Taraxacum officinale",
        "credit": "Enbéká",
        "license": "",
    },
    "plant_stellaria_media_l_vill": {
        "filename": "Stellaria media 117983654.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Stellaria_media_117983654.jpg",
        "alt": "Ptačinec žabinec",
        "caption": "Wikimedia Commons: Stellaria media",
        "credit": "Stephen James McWilliam",
        "license": "CC BY 4.0",
    },
    "plant_alliaria_petiolata_m_bieb_cavara_grande": {
        "filename": "Alliaria petiolata - P1040813.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Alliaria_petiolata_-_P1040813.jpg",
        "alt": "Česnáček lékařský",
        "caption": "Wikimedia Commons: Alliaria petiolata",
        "credit": "Lidine Mia",
        "license": "CC BY-SA 4.0",
    },
    "plant_bellis_perennis_l": {
        "filename": "Bellis perennis (1).jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Bellis_perennis_(1).jpg",
        "alt": "Sedmikráska chudobka",
        "caption": "Wikimedia Commons: Bellis perennis",
        "credit": "Sabina Bajracharya",
        "license": "CC BY-SA 4.0",
    },
    "plant_viola_odorata_l": {
        "filename": "Viola odorata (26346579005).jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Viola_odorata_(26346579005).jpg",
        "alt": "Violka vonná",
        "caption": "Wikimedia Commons: Viola odorata",
        "credit": "xulescu_g",
        "license": "CC BY-SA 2.0",
    },
    "plant_glechoma_hederacea_l": {
        "filename": "Glechoma hederacea.png",
        "source_url": "https://commons.wikimedia.org/wiki/File:Glechoma_hederacea.png",
        "alt": "Popenec břečťanolistý",
        "caption": "Wikimedia Commons: Glechoma hederacea",
        "credit": "Tiia Monto",
        "license": "CC BY-SA 4.0",
    },
    "plant_oxalis_acetosella_l": {
        "filename": "Oxalis acetosella.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Oxalis_acetosella.jpg",
        "alt": "Šťavel zaječí",
        "caption": "Wikimedia Commons: Oxalis acetosella",
        "credit": "Kjetil Lenes",
        "license": "Public domain",
    },
    "plant_rumex_acetosa": {
        "filename": "Rumex acetosa (7833427466).jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Rumex_acetosa_(7833427466).jpg",
        "alt": "Šťovík kyselý",
        "caption": "Wikimedia Commons: Rumex acetosa",
        "credit": "NPS / Jacob W. Frank",
        "license": "CC BY 2.0",
    },
    "plant_picea_abies": {
        "filename": "Picea-abies-shoot.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Picea-abies-shoot.jpg",
        "alt": "Mladý výhonek smrku ztepilého",
        "caption": "Wikimedia Commons: Picea abies young shoot",
        "credit": "Sten Porse",
        "license": "CC BY-SA 4.0",
    },
    "plant_fagus_sylvatica": {
        "filename": "Fagus sylvatica leaves.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Fagus_sylvatica_leaves.jpg",
        "alt": "Listy buku lesního",
        "caption": "Wikimedia Commons: Fagus sylvatica leaves",
        "credit": "Nicolas Weghaupt",
        "license": "",
    },
    "plant_crataegus_monogyna_jacq_c_laevigata_poir_dc": {
        "filename": "Leaves of Crataegus monogyna.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Leaves_of_Crataegus_monogyna.jpg",
        "alt": "Listy hlohu obecného",
        "caption": "Wikimedia Commons: Crataegus monogyna leaves",
        "credit": "Krzysztof Golik",
        "license": "CC BY-SA 4.0",
    },
    "plant_cardamine_pratensis": {
        "filename": "Cardamine pratensis (7833250474).jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Cardamine_pratensis_(7833250474).jpg",
        "alt": "Řeřišnice luční",
        "caption": "Wikimedia Commons: Cardamine pratensis",
        "credit": "NPS / Jacob W. Frank",
        "license": "CC BY 2.0",
    },
    "plant_allium_schoenoprasum": {
        "filename": "Allium schoenoprasum .jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Allium_schoenoprasum_.jpg",
        "alt": "Pažitka pobřežní",
        "caption": "Wikimedia Commons: Allium schoenoprasum",
        "credit": "Ghislain118 (AD)",
        "license": "CC BY-SA 3.0",
    },
    "plant_tilia_cordata_tilia_platyphyllos": {
        "filename": "20140605Tilia cordata7.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:20140605Tilia_cordata7.jpg",
        "alt": "Lípa srdčitá",
        "caption": "Wikimedia Commons: Tilia cordata",
        "credit": "AnRo0002",
        "license": "CC0",
    },
    "plant_pulmonaria_officinalis": {
        "filename": "Pulmonaria officinalis kpjas 27042008.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Pulmonaria_officinalis_kpjas_27042008.jpg",
        "alt": "Plicník lékařský",
        "caption": "Wikimedia Commons: Pulmonaria officinalis",
        "credit": "Kpjas",
        "license": "CC BY-SA 3.0",
    },
    "plant_cardamine_hirsuta": {
        "filename": "Cardamine hirsuta 37876.JPG",
        "source_url": "https://commons.wikimedia.org/wiki/File:Cardamine_hirsuta_37876.JPG",
        "alt": "Řeřišničník chlupatý",
        "caption": "Wikimedia Commons: Cardamine hirsuta",
        "credit": "Walter Siegmund",
        "license": "CC BY-SA 3.0",
    },
    "plant_veronica_beccabunga": {
        "filename": "Veronica beccabunga 001.JPG",
        "source_url": "https://commons.wikimedia.org/wiki/File:Veronica_beccabunga_001.JPG",
        "alt": "Rozrazil potoční",
        "caption": "Wikimedia Commons: Veronica beccabunga",
        "credit": "H. Zell",
        "license": "CC BY-SA 3.0",
    },
    "plant_anthriscus_sylvestris": {
        "filename": "Anthriscus sylvestris fluy 80 05052007 1.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Anthriscus_sylvestris_fluy_80_05052007_1.jpg",
        "alt": "Kerblík lesní",
        "caption": "Wikimedia Commons: Anthriscus sylvestris",
        "credit": "Olivier Pichard",
        "license": "CC BY-SA 3.0",
    },
    "plant_ulmus_glabra": {
        "filename": "Ulmus glabra-tr.JPG",
        "source_url": "https://commons.wikimedia.org/wiki/File:Ulmus_glabra-tr.JPG",
        "alt": "Jilm horský",
        "caption": "Wikimedia Commons: Ulmus glabra",
        "credit": "Karduelis",
        "license": "Public domain",
    },
    "plant_bunias_orientalis": {
        "filename": "Bunias orientalis kz37.jpg",
        "source_url": "https://commons.wikimedia.org/wiki/File:Bunias_orientalis_kz37.jpg",
        "alt": "Rukevník východní",
        "caption": "Wikimedia Commons: Bunias orientalis",
        "credit": "Krzysztof Ziarnek, Kenraiz",
        "license": "CC BY-SA 4.0",
    },
}


def backup_workbook(path: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = path.with_name(f"{path.stem}.backup_{timestamp}{path.suffix}")
    shutil.copy2(path, backup_path)
    return backup_path


def header_index_map(ws: openpyxl.worksheet.worksheet.Worksheet) -> dict[str, int]:
    headers = [cell.value for cell in ws[1]]
    return {str(value): index + 1 for index, value in enumerate(headers) if value is not None}


def upsert_rows(ws: openpyxl.worksheet.worksheet.Worksheet, key_field: str, rows: list[dict[str, str]]) -> tuple[int, int]:
    headers = header_index_map(ws)
    if key_field not in headers:
        raise KeyError(f"Missing key field {key_field} in sheet {ws.title}")

    existing = {}
    for row_index in range(2, ws.max_row + 1):
        key = ws.cell(row_index, headers[key_field]).value
        if key:
            existing[str(key)] = row_index

    inserted = 0
    updated = 0
    ordered_headers = [cell.value for cell in ws[1]]

    for row in rows:
        key = row[key_field]
        if key in existing:
            row_index = existing[key]
            updated += 1
        else:
            row_index = ws.max_row + 1
            inserted += 1

        for header in ordered_headers:
            if header is None:
                continue
            ws.cell(row=row_index, column=headers[str(header)], value=row.get(str(header), ""))

    return inserted, updated


def build_commons_src(file_name: str) -> str:
    return f"https://commons.wikimedia.org/wiki/Special:FilePath/{quote(file_name)}"


def update_manifest() -> tuple[int, int]:
    if MEDIA_MANIFEST_PATH.exists():
        manifest = json.loads(MEDIA_MANIFEST_PATH.read_text(encoding="utf-8"))
    else:
        manifest = {}

    created = 0
    updated = 0
    for plant_id, row in PHOTO_UPDATES.items():
        entry = {
            "src": build_commons_src(row["filename"]),
            "alt": row["alt"],
            "caption": row["caption"],
            "credit": row["credit"],
            "media_kind": "photo",
            "source_name": "Wikimedia Commons",
            "source_url": row["source_url"],
            "license": row["license"],
        }

        entries = manifest.get(plant_id, [])
        if not isinstance(entries, list):
            entries = []

        remaining = [item for item in entries if not (isinstance(item, dict) and item.get("src") == entry["src"])]
        if plant_id in manifest:
            updated += 1
        else:
            created += 1
        manifest[plant_id] = [entry, *remaining]

    MEDIA_MANIFEST_PATH.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return created, updated


def main() -> None:
    if not WORKBOOK_PATH.exists():
        raise FileNotFoundError(f"Workbook not found: {WORKBOOK_PATH}")

    backup_path = backup_workbook(WORKBOOK_PATH)
    workbook = openpyxl.load_workbook(WORKBOOK_PATH)

    zdroje_inserted, zdroje_updated = upsert_rows(workbook["Zdroje"], "zdroj_id", SOURCE_ROWS)
    starter_inserted, starter_updated = upsert_rows(workbook["Starter_dataset"], "record_id", STARTER_ROWS)
    trvanlive_inserted, trvanlive_updated = upsert_rows(workbook["Trvanlive_1m_plus"], "record_id", TRVANLIVE_ROWS)

    workbook.save(WORKBOOK_PATH)

    media_created, media_updated = update_manifest()

    print(f"Workbook backup: {backup_path}")
    print(f"Zdroje inserted={zdroje_inserted} updated={zdroje_updated}")
    print(f"Starter_dataset inserted={starter_inserted} updated={starter_updated}")
    print(f"Trvanlive_1m_plus inserted={trvanlive_inserted} updated={trvanlive_updated}")
    print(f"Media entries created={media_created} updated={media_updated}")


if __name__ == "__main__":
    main()
